input:
  stdin:
    scanner:
      lines:
        max_buffer_size: 524288

output:
  http_client:
    url: ${BIBLIO_BACKOFFICE_API_URL}/import-organizations
    verb: POST
    headers:
      Content-Type: application/json
      X-API-Key: ${BIBLIO_BACKOFFICE_API_KEY}
    max_in_flight: 40