input:
  label: ""
  mongodb:
    url: ${MONGODB_URL}
    database: ${MONGODB_DB}
    collection: ${MONGODB_COLLECTION}
    query: |
      {}

pipeline:
  processors:
    - mapping: |
        root.name = []
        root.name = if this.exists("title") {
          root.name.append({
            "lang": "und",
            "value": this.title
          })
        }

        root.description = []
        root.description = if this.exists("abstract") {
          root.description.append({
            "lang": "und",
            "value": this.abstract
          })
        }

        root.foundingDate = this.start_date.not_empty().catch(deleted())
        root.dissolutionDate = this.end_date.not_empty().catch(deleted())

        root.identifiers = []

        root.identifiers = if this.exists("iweto_id") {
          root.identifiers.append({
            "type": "iweto",
            "value": this.iweto_id
          })
        } else {
          root.identifiers.append({
            "type": "iweto",
            "value": this._id
          })
        }

        root.identifiers = if this.exists("gismo_id") {
          root.identifiers.append({
            "type": "gismo",
            "value": this.gismo_id
          })
        }

        root.identifiers = if this.exists("eu_id") {
          root.identifiers.append({
            "type": "cordis",
            "value": this.eu_id
          })
        }

        root.identifiers = if this.exists("ugent_id") {
          root.identifiers.merge(this.ugent_id.map_each(val -> {
            "type": "ugent",
            "value": val
          }))
        }

        root.attributes = []

        root.attributes = if this.exists("eu_acronym") {
          root.attributes.append({
            "scope": "gismo",
            "key": "eu_acronym",
            "value": this.eu_acronym
          })
        }

        root.attributes = if this.exists("eu_call_id") {
          root.attributes.append({
            "scope": "gismo",
            "key": "eu_call_id",
            "value": this.eu_call_id
          })
        }

        root.attributes = if this.exists("eu_framework_programme") {
          root.attributes.append({
            "scope": "gismo",
            "key": "eu_framework_programme",
            "value": this.eu_framework_programme
          })
        }

output:
  http_client:
    url: ${PROJECTS_API_ADD_PROJECT}
    verb: POST
    headers:
      Content-Type: application/json
      X-API-Key: ${PROJECTS_API_KEY}

